function createAppContext() {
  const constants = {
    RENDER_DELAY: 100,
    SCROLL_SYNC_DELAY: 10
  };

  const selectors = {
    markdownEditor: "markdown-editor",
    editorLineNumbers: "editor-line-numbers",
    editorCurrentLine: "editor-current-line",
    editorSelectionHighlights: "editor-selection-highlights",
    editorSyntaxHighlight: "editor-syntax-highlight",
    markdownPreview: "markdown-preview",
    themeToggle: "theme-toggle",
    restoreDefaultsButtons: ".restore-defaults-button",
    importFromFileButtons: "#import-from-file",
    newDocumentButtons: ".new-document-button",
    importFromGithubButton: "import-from-github",
    importFromFolderButton: "import-from-folder",
    folderTreePane: "folder-tree-pane",
    folderTreeFilterInput: "folder-tree-filter-input",
    createTagButton: "create-tag-button",
    deleteTagButton: "delete-tag-button",
    tagManagementSearch: "tag-management-search",
    tagManagementList: "tag-management-list",
    folderTreeFilterToggleButtons: ".toggle-folder-tree-filter",
    folderTreeExpandToggleButtons: ".toggle-folder-tree-expanded",
    folderTreeRoot: "folder-tree-root",
    fileInput: "file-input",
    folderInput: "folder-input",
    exportMd: "export-md",
    exportHtml: "export-html",
    exportPdf: "export-pdf",
    copyMarkdownButton: "copy-markdown-button",
    dropzone: "dropzone",
    closeDropzoneBtn: "close-dropzone",
    syncToggleButtons: ".sync-toggle-button",
    previewPane: ".preview-pane",
    readingTimeElement: "reading-time",
    wordCountElement: "word-count",
    charCountElement: "char-count",
    statusTipElement: "status-tip",
    graphZoomStatusElement: "graph-zoom-status",
    graphZoomPercentElement: "graph-zoom-percent",
    graphPointsStatusElement: "graph-points-status",
    graphPointsCountElement: "graph-points-count",
    editorTextpadStatusElement: "editor-textpad-status",
    editorTotalLengthElement: "editor-total-length",
    editorTotalLinesElement: "editor-total-lines",
    editorCursorLineElement: "editor-cursor-line",
    editorCursorColumnElement: "editor-cursor-column",
    editorPositionLabelElement: "editor-position-label",
    editorPositionValueElement: "editor-position-value"
  };

  const dom = {
    markdownEditor: document.getElementById(selectors.markdownEditor),
    editorLineNumbers: document.getElementById(selectors.editorLineNumbers),
    editorCurrentLine: document.getElementById(selectors.editorCurrentLine),
    editorSelectionHighlights: document.getElementById(selectors.editorSelectionHighlights),
    editorSyntaxHighlight: document.getElementById(selectors.editorSyntaxHighlight),
    markdownPreview: document.getElementById(selectors.markdownPreview),
    themeToggle: document.getElementById(selectors.themeToggle),
    restoreDefaultsButtons: document.querySelectorAll(selectors.restoreDefaultsButtons),
    importFromFileButtons: document.querySelectorAll(selectors.importFromFileButtons),
    newDocumentButtons: document.querySelectorAll(selectors.newDocumentButtons),
    importFromGithubButton: document.getElementById(selectors.importFromGithubButton),
    importFromFolderButton: document.getElementById(selectors.importFromFolderButton),
    folderTreeFilterInput: document.getElementById(selectors.folderTreeFilterInput),
    createTagButton: document.getElementById(selectors.createTagButton),
    deleteTagButton: document.getElementById(selectors.deleteTagButton),
    tagManagementSearch: document.getElementById(selectors.tagManagementSearch),
    tagManagementList: document.getElementById(selectors.tagManagementList),
    folderTreeFilterToggleButtons: document.querySelectorAll(selectors.folderTreeFilterToggleButtons),
    folderTreeExpandToggleButtons: document.querySelectorAll(selectors.folderTreeExpandToggleButtons),
    folderTreeRoot: document.getElementById(selectors.folderTreeRoot),
    fileInput: document.getElementById(selectors.fileInput),
    folderInput: document.getElementById(selectors.folderInput),
    exportMd: document.getElementById(selectors.exportMd),
    exportHtml: document.getElementById(selectors.exportHtml),
    exportPdf: document.getElementById(selectors.exportPdf),
    copyMarkdownButton: document.getElementById(selectors.copyMarkdownButton),
    dropzone: document.getElementById(selectors.dropzone),
    closeDropzoneBtn: document.getElementById(selectors.closeDropzoneBtn),
    syncToggleButtons: document.querySelectorAll(selectors.syncToggleButtons),
    editorPane: document.getElementById(selectors.markdownEditor),
    previewPane: document.querySelector(selectors.previewPane),
    readingTimeElement: document.getElementById(selectors.readingTimeElement),
    wordCountElement: document.getElementById(selectors.wordCountElement),
    charCountElement: document.getElementById(selectors.charCountElement),
    statusTipElement: document.getElementById(selectors.statusTipElement),
    graphZoomStatusElement: document.getElementById(selectors.graphZoomStatusElement),
    graphZoomPercentElement: document.getElementById(selectors.graphZoomPercentElement),
    graphPointsStatusElement: document.getElementById(selectors.graphPointsStatusElement),
    graphPointsCountElement: document.getElementById(selectors.graphPointsCountElement),
    editorTextpadStatusElement: document.getElementById(selectors.editorTextpadStatusElement),
    editorTotalLengthElement: document.getElementById(selectors.editorTotalLengthElement),
    editorTotalLinesElement: document.getElementById(selectors.editorTotalLinesElement),
    editorCursorLineElement: document.getElementById(selectors.editorCursorLineElement),
    editorCursorColumnElement: document.getElementById(selectors.editorCursorColumnElement),
    editorPositionLabelElement: document.getElementById(selectors.editorPositionLabelElement),
    editorPositionValueElement: document.getElementById(selectors.editorPositionValueElement)
  };

  const state = {
    markdownRenderTimeout: null,
    syncScrollingEnabled: true,
    isEditorScrolling: false,
    isPreviewScrolling: false,
    scrollSyncTimeout: null,
    currentViewMode: "split",
    autoSelectFileEnabled: true,
    currentFolderTreeNodes: [],
    folderTreeFilterText: "",
    selectedFolderTreeTags: new Set(),
    currentFolderSortMode: "name-asc",
    showUnsupportedFolderFiles: false,
    isFolderOpen: false,
    shownFolderInputFallbackNotice: false,
    previewHoveredLinkUrl: "",
    linkAutocompleteLayer: null,
    linkAutocompleteState: null
  };

  console.error("[FolderTree] init", {
    hasPane: !!document.getElementById(selectors.folderTreePane),
    hasRoot: !!dom.folderTreeRoot,
    hasImportOption: !!dom.importFromFolderButton,
    viewportWidth: window.innerWidth
  });

  return {
    dom,
    state,
    constants,
    actions: {},
    selectors,
    services: {}
  };
}
