@echo off
setlocal

set "DESKTOP_DIR=%~dp0"
set "RESOURCES_DIR=%DESKTOP_DIR%resources"
set "RESOURCE_JS_DIR=%RESOURCES_DIR%\js"

if not exist "%DESKTOP_DIR%neutralino.config.json" (
    echo Desktop app folder was not found or is incomplete: "%DESKTOP_DIR%"
    exit /b 1
)

echo Cleaning generated desktop deployment files...
echo.

if exist "%DESKTOP_DIR%dist\" rmdir /s /q "%DESKTOP_DIR%dist"
if exist "%DESKTOP_DIR%.tmp\" rmdir /s /q "%DESKTOP_DIR%.tmp"
if exist "%DESKTOP_DIR%neutralinojs.log" del /f /q "%DESKTOP_DIR%neutralinojs.log"
if exist "%DESKTOP_DIR%webview2-repair.log" del /f /q "%DESKTOP_DIR%webview2-repair.log"

rem Prepared resources copied or generated by desktop setup/prepare.
rem Keep desktop-app\bin and resources\vendor so offline desktop PCs keep cached dependencies.
if exist "%RESOURCES_DIR%\assets\" rmdir /s /q "%RESOURCES_DIR%\assets"
if exist "%RESOURCES_DIR%\wiki\" rmdir /s /q "%RESOURCES_DIR%\wiki"
if exist "%RESOURCES_DIR%\index.html" del /f /q "%RESOURCES_DIR%\index.html"
if exist "%RESOURCES_DIR%\styles.css" del /f /q "%RESOURCES_DIR%\styles.css"

rem Prepared JavaScript copied from web-app/js/ and web-app/script.js.
rem Keep desktop-owned resources/js/main.js and resources/js/neutralino.*.
if exist "%RESOURCE_JS_DIR%\core\" rmdir /s /q "%RESOURCE_JS_DIR%\core"
if exist "%RESOURCE_JS_DIR%\editor\" rmdir /s /q "%RESOURCE_JS_DIR%\editor"
if exist "%RESOURCE_JS_DIR%\export\" rmdir /s /q "%RESOURCE_JS_DIR%\export"
if exist "%RESOURCE_JS_DIR%\files\" rmdir /s /q "%RESOURCE_JS_DIR%\files"
if exist "%RESOURCE_JS_DIR%\graph\" rmdir /s /q "%RESOURCE_JS_DIR%\graph"
if exist "%RESOURCE_JS_DIR%\import\" rmdir /s /q "%RESOURCE_JS_DIR%\import"
if exist "%RESOURCE_JS_DIR%\markdown\" rmdir /s /q "%RESOURCE_JS_DIR%\markdown"
if exist "%RESOURCE_JS_DIR%\platform\" rmdir /s /q "%RESOURCE_JS_DIR%\platform"
if exist "%RESOURCE_JS_DIR%\recent\" rmdir /s /q "%RESOURCE_JS_DIR%\recent"
if exist "%RESOURCE_JS_DIR%\sidebar\" rmdir /s /q "%RESOURCE_JS_DIR%\sidebar"
if exist "%RESOURCE_JS_DIR%\tabs\" rmdir /s /q "%RESOURCE_JS_DIR%\tabs"
if exist "%RESOURCE_JS_DIR%\tags\" rmdir /s /q "%RESOURCE_JS_DIR%\tags"
if exist "%RESOURCE_JS_DIR%\ui\" rmdir /s /q "%RESOURCE_JS_DIR%\ui"
if exist "%RESOURCE_JS_DIR%\app.js" del /f /q "%RESOURCE_JS_DIR%\app.js"
if exist "%RESOURCE_JS_DIR%\clipboard.js" del /f /q "%RESOURCE_JS_DIR%\clipboard.js"
if exist "%RESOURCE_JS_DIR%\keyboard-shortcuts.js" del /f /q "%RESOURCE_JS_DIR%\keyboard-shortcuts.js"
if exist "%RESOURCE_JS_DIR%\MIGRATION.md" del /f /q "%RESOURCE_JS_DIR%\MIGRATION.md"
if exist "%RESOURCE_JS_DIR%\script.js" del /f /q "%RESOURCE_JS_DIR%\script.js"
if exist "%RESOURCE_JS_DIR%\scroll-sync.js" del /f /q "%RESOURCE_JS_DIR%\scroll-sync.js"
if exist "%RESOURCE_JS_DIR%\share-url.js" del /f /q "%RESOURCE_JS_DIR%\share-url.js"
if exist "%RESOURCE_JS_DIR%\unsaved-changes.js" del /f /q "%RESOURCE_JS_DIR%\unsaved-changes.js"

echo Desktop undeploy cleanup complete.
exit /b 0
