const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const resources = path.resolve(__dirname, "../resources");
const panelSource = fs.readFileSync(path.join(resources, "js/image-editor/layers/adjustments/adjustments-panel.js"), "utf8");
const viewSource = fs.readFileSync(path.join(resources, "js/image-editor/view.js"), "utf8");
const stylesSource = fs.readFileSync(path.join(resources, "styles.css"), "utf8");
const htmlSource = fs.readFileSync(path.join(resources, "index.html"), "utf8");

test("adjustment inspector exposes the requested tabs, catalog item, and property bounds", () => {
  assert.match(panelSource, /data-adjustment-tab="properties">Properties/);
  assert.match(panelSource, /data-adjustment-tab="adjustments">Adjustments/);
  assert.match(panelSource, /create-brightness-contrast/);
  assert.match(panelSource, /create-exposure/);
  assert.match(panelSource, /create-vibrance/);
  assert.match(panelSource, /create-hue-saturation/);
  assert.match(panelSource, /create-color-balance/);
  assert.match(panelSource, /create-black-white/);
  assert.match(panelSource, /create-channel-mixer/);
  assert.match(panelSource, /create-levels/);
  assert.match(panelSource, /create-curves/);
  assert.match(panelSource, /create-photo-filter/);
  assert.match(panelSource, /create-invert/);
  assert.match(panelSource, /create-selective-color/);
  assert.match(panelSource, /create-match-color/);
  assert.match(panelSource, /create-replace-color/);
  assert.match(panelSource, /propertyControl\("Brightness", "brightness", -150, 150/);
  assert.match(panelSource, /propertyControl\("Contrast", "contrast", -50, 100/);
  assert.match(panelSource, /propertyControl\("Exposure", "exposure", -20, 20/);
  assert.match(panelSource, /propertyControl\("Offset", "offset", -\.5, \.5/);
  assert.match(panelSource, /propertyControl\("Gamma Correction", "gamma", \.01, 9\.99/);
  assert.match(panelSource, /propertyControl\("Vibrance", "vibrance", -100, 100/);
  assert.match(panelSource, /propertyControl\("Saturation", "saturation", -100, 100/);
  assert.match(panelSource, /propertyControl\("Hue", "hue", -180, 180/);
  assert.match(panelSource, /propertyControl\("Lightness", "lightness", -100, 100/);
  assert.match(panelSource, /data-adjustment-range=/);
  assert.match(panelSource, /data-adjustment-toggle="colorize"/);
  assert.match(panelSource, /data-adjustment-select="tone"/);
  assert.match(panelSource, /data-adjustment-toggle="preserveLuminosity"/);
  assert.match(panelSource, /tone \+ "CyanRed"/);
  assert.match(panelSource, /propertyControl\("Cyan  -  Red", tone \+ "CyanRed", -100, 100/);
  assert.match(panelSource, /propertyControl\("Magenta  -  Green", tone \+ "MagentaGreen", -100, 100/);
  assert.match(panelSource, /propertyControl\("Yellow  -  Blue", tone \+ "YellowBlue", -100, 100/);
  assert.match(panelSource, /data-adjustment-toggle="blackWhiteTint"/);
  assert.match(panelSource, /data-adjustment-color="tintColor"/);
  assert.match(panelSource, /data-adjustment-panel-action="black-white-auto"/);
  assert.match(panelSource, /propertyControl\("Reds", "reds", -200, 300/);
  assert.match(panelSource, /propertyControl\("Magentas", "magentas", -200, 300/);
  assert.match(panelSource, /data-adjustment-select="outputChannel"/);
  assert.match(panelSource, /data-adjustment-toggle="channelMixerMonochrome"/);
  assert.match(panelSource, /data-channel-mixer-total/);
  assert.match(panelSource, /propertyControl\("Constant", prefix \+ "Constant", -200, 200/);
  assert.match(panelSource, /data-adjustment-select="levelsChannel"/);
  assert.match(panelSource, /data-adjustment-panel-action="levels-auto"/);
  assert.match(panelSource, /image-editor-levels-histogram/);
  assert.match(panelSource, /propertyControl\("Gamma", channel \+ "Gamma", \.1, 9\.99/);
  assert.match(panelSource, /curvesProperties\.controls/);
  assert.match(panelSource, /curvesProperties\.autoPatch/);
  const curvesSource = fs.readFileSync(path.join(resources, "js/image-editor/layers/adjustments/curves-properties.js"), "utf8");
  assert.match(curvesSource, /image-editor-curves-graph/);
  assert.match(curvesSource, /data-curves-coordinate="input"/);
  assert.match(curvesSource, /Delete Curves point/);
  const photoFilterSource = fs.readFileSync(path.join(resources, "js/image-editor/layers/adjustments/photo-filter-properties.js"), "utf8");
  assert.match(photoFilterSource, /data-photo-filter-mode/);
  assert.match(photoFilterSource, /data-photo-filter-preset/);
  assert.match(photoFilterSource, /data-photo-filter-color/);
  assert.match(photoFilterSource, /propertyControl\("Density", "density", 1, 100/);
  assert.match(photoFilterSource, /data-photo-filter-preserve/);
  const selectiveColorSource = fs.readFileSync(path.join(resources, "js/image-editor/layers/adjustments/selective-color-properties.js"), "utf8");
  assert.match(selectiveColorSource, /data-selective-color-range/);
  assert.match(selectiveColorSource, /data-selective-color-method/);
  assert.match(selectiveColorSource, /propertyControl\("Cyan", selected \+ "Cyan", -100, 100/);
  assert.match(selectiveColorSource, /propertyControl\("Black", selected \+ "Black", -100, 100/);
  const matchColorSource = fs.readFileSync(path.join(resources, "js/image-editor/layers/adjustments/match-color-properties.js"), "utf8");
  assert.match(matchColorSource, /data-match-color-source/);
  assert.match(matchColorSource, /data-match-color-neutralize/);
  assert.match(matchColorSource, /propertyControl\("Luminance", "luminance", 1, 200/);
  assert.match(matchColorSource, /propertyControl\("Color Intensity", "colorIntensity", 1, 200/);
  assert.match(matchColorSource, /propertyControl\("Fade", "fade", 0, 100/);
  const replaceColorSource = fs.readFileSync(path.join(resources, "js/image-editor/layers/adjustments/replace-color-properties.js"), "utf8");
  assert.match(replaceColorSource, /data-replace-color-source/);
  assert.match(replaceColorSource, /data-replace-color-sample/);
  assert.match(replaceColorSource, /propertyControl\("Fuzziness", "fuzziness", 0, 200/);
  assert.match(replaceColorSource, /propertyControl\("Hue", "hue", -180, 180/);
  assert.match(panelSource, /data-adjustment-mask-action="invert"/);
  assert.match(panelSource, /data-adjustment-mask-action="white"/);
  assert.match(panelSource, /data-adjustment-mask-action="black"/);
});

test("adjustment inspector is a fixed stage overlay with a dedicated toolbar toggle", () => {
  assert.match(stylesSource, /\.image-editor-adjustments-panel\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?top:\s*12px;[\s\S]*?right:\s*12px;/);
  assert.match(viewSource, /adjustmentsButton\.dataset\.adjustmentsToggle = "true"/);
  assert.match(htmlSource, /layers\/adjustments\/adjustments-panel\.js/);
  assert.match(htmlSource, /layers\/adjustments\/brightness-contrast-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/exposure-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/vibrance-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/hue-saturation-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/color-balance-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/black-white-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/channel-mixer-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/levels-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/curves-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/curves-properties\.js/);
  assert.match(htmlSource, /layers\/adjustments\/photo-filter-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/photo-filter-properties\.js/);
  assert.match(htmlSource, /layers\/adjustments\/invert-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/selective-color-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/selective-color-properties\.js/);
  assert.match(htmlSource, /layers\/adjustments\/match-color-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/match-color-properties\.js/);
  assert.match(htmlSource, /layers\/adjustments\/replace-color-adjustment\.js/);
  assert.match(htmlSource, /layers\/adjustments\/replace-color-properties\.js/);
});

test("adjustment inspector persists per-tab mode, height, and active tab state", () => {
  assert.match(panelSource, /mode:\s*\["expanded", "minimized", "hidden"\]/);
  assert.match(panelSource, /height:\s*Math\.max\(220/);
  assert.match(panelSource, /activeTab:\s*options\.state\?\.activeTab/);
  assert.match(panelSource, /onStateChanged\(\{ \.\.\.this\.state \}\)/);
});
